### ISSUE TITLE
REQUEST: allow working with more than model

### ISSUE THREAD

**Issue by ZTThomasOberthanner** [Dlubal-Software/RFEM_Python_Client#103]
**current situation**
Model stores clientModel as a class attribute so you it is not possible to work with more than one file

**preferred solution**
use a instance variable instead
`self.clientModel`

**Comment by OndraMichal** [comment]
Hi @ZTThomasOberthanner,
the SUDS module which facilates connection enables only one connection. But there is no problem switching between the model inside one connection. I can add a function to switch between the models to make it easier. Class Model() represents model not application. See [application methods](https://github.com/Dlubal-Software/RFEM_Python_Client/wiki/Methods-and-Types-for-Application) to see how it works.

**Comment by ZTThomasOberthanner** [comment]
that would be great because I have a use case, where many models interact with each other
