### ISSUE TITLE
REQUEST: Query model

### ISSUE THREAD

**Issue by ZTThomasOberthanner** [Dlubal-Software/RFEM_Python_Client#105]
How do I query the model, e.g. for existing nodes, members, internal forces and so on?

**Comment by OndraMichal** [comment]
Hi @ZTThomasOberthanner,
thank you for thr question. To query the model you start with initializing the connection. This can be done via `Model(False, "model_name")`. Then use any getter you need to retrieve the data. Our unit tests (RFEM_Python_Client/UnitTests/) are good examples of setting values and getting them back for checking correctness. But in the tests we use currently available (active) model, that is why you see just `Model()` there.
If you want to see all available model functions and types (prefix ns0:), just initialize class Model and then `print(Model.clientModel)`. This is the easiest way SUDS module shows everything it recognizes.
I'll add this process to our Wiki.

**Comment by ZTThomasOberthanner** [comment]
Thanks for the quick reply, i did had a look at test_Member_test.py but I could not find any tests for correctness there. 
I am now able to get node/member information from the model. But I cannot figure out how to get the internal forces for a member for a certain loadcase/result combination. Would by happy for another hint.

**Comment by DavidNaizheZhou** [comment]
is it possible to query a list/table of all nodes, members, ...?

suggestion:
get_node() - function with a default None

get_node(xs=None) -> provides the nodes table as (DataFrame or a Dict)
![image](https://user-images.githubusercontent.com/70525024/160089860-49d17c3e-fb1f-4b12-9739-6aeb401f96d6.png)

**Comment by dogukankaratas** [comment]
Hey, thanks for bringing this up and ideas. I would like to jump back the question and drop here a suggestion. Here is a function  to create DataFrame tables for Node objects. 

```python
def getNodeTable():
        import pandas as pd
        nodeTable = pd.DataFrame(columns=["Node No.", "X", "Y", "Z"])
        modelStatus = GetModelInfo()
        for i in range(1, modelStatus[0] + 1):
            nodeTable.loc[i] = [i, Model.clientModel.service.get_node(i)['coordinate_1'],
                                   Model.clientModel.service.get_node(i)['coordinate_2'],
                                   Model.clientModel.service.get_node(i)['coordinate_2']]

        return nodeTable
```
The same logic will work for another objects (lines, members, surfaces etc.). 

Maybe this functions can be added to our static methods. Please let me know about your thoughts  :v:

**Comment by DavidNaizheZhou** [comment]
Here is my suggestion...with the parameter type you can choose the object

```ruby

import pandas as pd
import numpy as np

from RFEM.initModel import Model, ConvertStrToListOfInt
from RFEM.BasicObjects.node import Node
from RFEM.BasicObjects.material import Material
from RFEM.BasicObjects.section import Section


def load_nodes(clientModel, type="NODE"):
    numbers = ConvertStrToListOfInt(
        clientModel.service.get_all_object_numbers(
            type="E_OBJECT_TYPE_{}".format(type.upper())
        )
    )
    return [Model.clientModel.service.get_node(int(n)) for n in numbers]


def load_dataframe(clientModel, type="NODE"):
    nodes_list = load_nodes(clientModel, type)
    len_numbers = len(nodes_list)
    keys = dict(nodes_list[0]).keys()
    dataframe = pd.DataFrame(columns=keys, index=range(len_numbers), dtype=object)
    for i, node in enumerate(nodes_list):
        node_dict = dict(node)
        values = node_dict.values()
        dataframe.iloc[i] = np.array([value for value in values], dtype=object)
    return dataframe


Model(new_model=True, model_name="extract_dataframe")

# model modification
Model.clientModel.service.begin_modification()
Node(1, 0.0, 0.0, 0.0)
Node(2, 1.0, 0.0, 0.0)
Node(3, 2.0, 0.0, 0.0)
Model.clientModel.service.finish_modification()

# load dataframe
df = load_dataframe(Model.clientModel, type="NODE")
print(df)

```

**Comment by DavidNaizheZhou** [comment]
here is my suggestion:

```ruby
from RFEM.initModel import Model, ConvertStrToListOfInt
from RFEM.BasicObjects.node import Node
from RFEM.BasicObjects.material import Material
from RFEM.BasicObjects.section import Section


def load_nodes(clientModel, type="NODE"):
    numbers = ConvertStrToListOfInt(
        clientModel.service.get_all_object_numbers(
            type="E_OBJECT_TYPE_{}".format(type.upper())
        )
    )
    if type.upper()=="NODE":
        return [Model.clientModel.service.get_node(int(n)) for n in numbers]
    else:
        # todo object types
        pass
        

def load_dataframe(clientModel, type="NODE"):
    nodes_list = load_nodes(clientModel, type)
    len_numbers = len(nodes_list)
    keys = dict(nodes_list[0]).keys()
    dataframe = pd.DataFrame(columns=keys, index=range(len_numbers), dtype=object)
    for i, node in enumerate(nodes_list):
        node_dict = dict(node)
        values = node_dict.values()
        dataframe.iloc[i] = np.array([value for value in values], dtype=object)
    return dataframe


Model(new_model=True, model_name="extract_dataframe")

# model modification
Model.clientModel.service.begin_modification()
Node(1, 0.0, 0.0, 0.0)
Node(2, 1.0, 0.0, 0.0)
Node(3, 2.0, 0.0, 0.0)
Model.clientModel.service.finish_modification()

# extract table
df = load_dataframe(Model.clientModel, type="NODE")
print(df)

```

**Comment by ZTThomasOberthanner** [comment]
just a reminder:
clientModel.service.get_all_object_numbers already returns a list of int - so no need for ConvertStrToListOfInt...
```
numbers = ConvertStrToListOfInt(
        clientModel.service.get_all_object_numbers(
            type="E_OBJECT_TYPE_{}".format(type.upper())
        )
    )
```

**Comment by dogukankaratas** [comment]
Since everyone has a solution, this issue will be closed 😃 Thanks for contribution.
