### ISSUE TITLE
REQUEST: Select items 

### ISSUE THREAD

**Issue by ZTThomasOberthanner** [Dlubal-Software/RFEM_Python_Client#117]
**UI: How can the user pick some elements, eg. nodes?**
in RFEM5 it was possible to use `PickObjects` to get a small dialog and let the user select e.g. Nodes / Members. the function returns a list of numbers that was selected.
![image](https://user-images.githubusercontent.com/92015468/161247973-f9dbdc35-6e18-4755-b37d-b87a5f5b8563.png)

How can this done in RFEM6?

**Comment by dogukankaratas** [comment]
Hi,
This question is relevant to main program features, not with Python library. Please take a look at the online manual.
https://www.dlubal.com/en/downloads-and-information/documents/online-manuals/rfem-6/000936

**Comment by ZTThomasOberthanner** [comment]
After reading the online manual I only find ways to select object using rfems native UI. But my question is, how can this done using the soap API?

In RFEM5 it was possible to use the `PickObjects` method to pause the execution of the code and let the user pick objects using the dialog shown above. After clicking OK the selected numbers were returned to the program. It is like the `input()` method in python. 

![image](https://user-images.githubusercontent.com/92015468/161695266-83b1bbfb-3515-4c58-aad4-b70993ad03d3.png)

**Comment by ZTThomasOberthanner** [comment]
i have created a feature request on the dlubal homepage - i think this is missing in the soap api
