### ISSUE TITLE
REQUEST: Installing Without Downgrading Setuptools 

### ISSUE THREAD

**Issue by cslotboom** [Dlubal-Software/RFEM_Python_Client#122]
**Is your feature request related to a problem? Please describe.**
The RFEM Python client depends on suds_requests, which also depends on 'use_2to3' from setuptools for it's installation. This was removed from setuptools in 58 - https://setuptools.pypa.io/en/latest/history.html#v58-0-0
[github/suds_requests#12](https://github.com/armooo/suds_requests/issues/12)

**Describe the solution you'd like**
In the short term, downgrading setuptools and installing is sufficient, but a cleaner long-term solution would be preferred. The desired solution would ideally work with the latest versions of setup-tools, and work "out of the box" without any tinkering with environments. I understand this might be tricky however, many of these packages are out of Dlubal's control..

**Comment by OndraMichal** [comment]
Hi @cslotboom,
thank you for your interest in our Python Client. If you inspect the module you will find that the author uses `setuptools` only for non-functional file `setup.py`. We can omit it by transferring the function code to our Client. This module is under the MIT license.

**Comment by cslotboom** [comment]
Hey, great to see this resolved! It will make managing the environment much easier!
