### ISSUE TITLE
BUG: SteelMemberLocalSectionReduction 

### ISSUE THREAD

**Issue by heetpatel96** [Dlubal-Software/RFEM_Python_Client#147]
Getting error in branch : heet-memberLocalSectionReduction

after importing and calling SteelMemberLocalSectionReduction in example(Demo2), It raises WebFault: b"Server raised fault: 'Enumeration item '' not found.'"

**Comment by OndraMichal** [comment]
Fixed the issue in commit [2dccc1b920beaa95937df05c3272987c627c430c](https://github.com/Dlubal-Software/RFEM_Python_Client/commit/2dccc1b920beaa95937df05c3272987c627c430c).

**Comment by OndraMichal** [comment]
Fixed. Pushed to main.
