### ISSUE TITLE
BUG: Mixed types for get_results_for_nodes_support_forces --> ResultTables.NodesSupportForces

### ISSUE THREAD

**Issue by damianbobrowski** [Dlubal-Software/RFEM_Python_Client#158]
**Describe the bug**
`get_results_for_nodes_support_forces` returns different types for px, py, pz, mx, my, mz

**To Reproduce**

call for WebService directly:

`get_results_for_nodes_support_forces`

or for python:

```python
    result_list =  ResultTables.NodesSupportForces(loading_type=loading_type, loading_no=loading_no, object_no=1)

    # check types
    for entry in result_list:
        for key, value in entry.items():
            print(key, type(value))

    # write to json
    result_dict = {}
    for index, entry in enumerate(result_list):
        result_dict[index] = entry

    with open("C:\Dev\RFEM_Python_Client-main\RFEM_Python_Client-main\Examples\Cantilever\ResultTables\_Nodes_support_forces.json", "w") as file:
        file.write(json.dumps(result_dict, indent=2))
```

**Expected behavior**
One type for: px, py, pz, mx, my, mz.
Looking at deformation ResultTables.NodesDeformation I would expected float type for all

**Screenshots**
![image](https://user-images.githubusercontent.com/26790705/191692649-d4a59c8f-64f9-4111-bd93-365ccb9a2107.png)

![image](https://user-images.githubusercontent.com/26790705/191687821-20155c44-0ddf-4c2a-b5e9-baa270c698d2.png)

**Desktop (please complete the following information):**
 - Version of WIN10 OS: [WIN 10]
 - Version of RFEM6: [6.02.0030]
 - Version of tool [1.11.0]

**Comment by OndraMichal** [comment]
Hi @damianbobrowski,
thank you for taking an interest. If you take a look at RFEM result tables, sometimes there is string where float should be. That is why, I think, we are getting mixed types. Anyway I resolved it in branch [OndrejMichal-MixedResultTypes](https://github.com/Dlubal-Software/RFEM_Python_Client/compare/main...OndrejMichal-MixedResultTypes). I strongly recommend to use our ResultTables class. That way it will be all floats if possible.
![image](https://user-images.githubusercontent.com/37547309/191753937-25efa0c1-9d47-433f-92e0-1574246db185.png)
