### ISSUE TITLE
REQUEST:  "atributes" typo related to clearAtributes() at RFEM.initModels

### ISSUE THREAD

**Issue by damianbobrowski** [Dlubal-Software/RFEM_Python_Client#160]
**Is your feature request related to a problem? Please describe.**
Not a big deal: Just Code Spell Checker for VSCode reports problem.

**Describe the solution you'd like**
clearAtributes() --> clearAttributes()
atributes --> attributes

**Comment by OndraMichal** [comment]
Thank you for the notice. Fixed in OndrejMichal-MixedResultTypes branch.
