### ISSUE TITLE
REQUEST: support for get_all_object_numbers_by_type

### ISSUE THREAD

**Issue by damianbobrowski** [Dlubal-Software/RFEM_Python_Client#161]
**Is your feature request related to a problem? Please describe.**
It seems like `get_all_object_numbers_by_type` is not supported yet.
I would like to get all object numbers it case when ResultTables data dump is needed for all object with specific Type

**Describe the solution you'd like**

Example patch I right now use:
``` python
import enum

from RFEM.initModel import Model
from RFEM.enums import ObjectTypes


def GetNumbers(object_numbers):
    lstOfNumbers = []

    if object_numbers:
        for on in object_numbers[0]:
            lstOfNumbers.append(on.no)
        return lstOfNumbers
    else:
        return None


class ObjectNumbers():

    @staticmethod
    def GetAllObjectNumbersByType(
        type_: enum = ObjectTypes.E_OBJECT_TYPE_NODE,
        model = Model
        ):

        object_numbers = model.clientModel.service.get_all_object_numbers_by_type(type_.name)
        return GetNumbers(object_numbers)
```

Call:
```python
print(ObjectNumbers.GetAllObjectNumbersByType(ObjectTypes.E_OBJECT_TYPE_NODE))
print(ObjectNumbers.GetAllObjectNumbersByType(ObjectTypes.E_OBJECT_TYPE_MEMBER))
print(ObjectNumbers.GetAllObjectNumbersByType(ObjectTypes.E_OBJECT_TYPE_SOLID_GAS))
```

Result:
```
[9, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 25, 26, 27, 28, 33, 34, 35, 36]
[9, 1, 2, 3, 4, 5, 6, 7, 8]
None
```

**Comment by OndraMichal** [comment]
Hi @damianbobrowski,
thank you for letting us know. Will add it to the client. The benefit of the open source solution is that everybody can contribute so if you have the time don't shy away from adding your solution to the client and create pull request. We will gladly put you as collaborator 👍

**Comment by damianbobrowski** [comment]
Hi @OndraMichal 
next time I will try to create PR instead of opening Issues.

**Comment by OndraMichal** [comment]
PR #182 will add this function.

**Comment by OndraMichal** [comment]
PR #182 is merged to main.
