### ISSUE TITLE
BUG: Package RFEM does not contains used *.js, *.css, *.png

### ISSUE THREAD

**Issue by damianbobrowski** [Dlubal-Software/RFEM_Python_Client#163]
**Describe the bug**
Files *.js, *.css, *.png are not send with RFEM package, they exit on repository:
https://github.com/Dlubal-Software/RFEM_Python_Client/tree/main/RFEM/Reports.

They are used here:
https://github.com/Dlubal-Software/RFEM_Python_Client/blob/main/RFEM/Reports/html.py#L275

```
    copy(os.path.join(dirname, 'htmlStyles.css'), TargetFolderPath)
    copy(os.path.join(dirname, 'htmlScript.js'), TargetFolderPath)
    copy(os.path.join(dirname, 'favicon32.png'), TargetFolderPath)
```

As result  it is not possible to generate HTML report out of the box.

**To Reproduce**
1. pip install RFEM
2. see content of RFEM.Reports

**Expected behavior**
Used files are packed with package, not only exists on repository

**Screenshots**
![image](https://user-images.githubusercontent.com/26790705/191905234-978abbbd-67b6-4d9f-b5f1-5d2801c03b42.png)

**Desktop (please complete the following information):**
 - Version of WIN10 / Linux
 - Version of tool [e.g. 1.11.0]

**Comment by OndraMichal** [comment]
Those 3 files are now in the pypi pkg. v1.13.0.
