### ISSUE TITLE
ActionCategory and DesignSituation vs matching Standard+Annex

### ISSUE THREAD

**Issue by dogukankaratas** [Dlubal-Software/RFEM_Python_Client#183]
### Discussed in https://github.com/Dlubal-Software/RFEM_Python_Client/discussions/178

<div type='discussions-op-text'>

<sup>Originally posted by **damianbobrowski** September 30, 2022</sup>
Hello

Is there any programmatic way or documentation available to get know **which Action Category** from list of 258 elements:
https://github.com/Dlubal-Software/RFEM_Python_Client/blob/main/RFEM/enums.py#L1851

**is true** for given `current_standard_for_combination_wizard` documented via doc string here:
https://github.com/Dlubal-Software/RFEM_Python_Client/blob/main/RFEM/LoadCasesAndCombinations/loadCasesAndCombinations.py#L21

For example for NATIONAL_ANNEX_AND_EDITION_EN_1990_CEN_2010_04 we have 18 Action Categories matched

![image](https://user-images.githubusercontent.com/26790705/193271333-cd9330a3-f275-47ef-b32b-24b50757efab.png)

**Edit** [03.10.2022]
This question is relevant also for DesignSituationType
https://github.com/Dlubal-Software/RFEM_Python_Client/blob/main/RFEM/enums.py#L1920
![image](https://user-images.githubusercontent.com/26790705/193569449-fc9e3cb3-f2c7-4a2c-9172-83468a46e95c.png)

</div>

**Comment by Bjoern-Steinhagen** [comment]
Action to be taken: 

- Function to be included within loadCasesAndCombinations.py which returns a list of possible / valid load action categories
- The function will read the defined standard of the model and respond appropriately
