### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by BjornSchweder** [Dlubal-Software/RFEM_Python_Client#227]
**Describe the bug**
LoadCombination(...) Yields: "AttributeError: 'NoneType' object has no attribute 'factor'
in
...\Rfem\LoadCasesAndCombinations\loadCombinations.py 
at mlvlp.row.factor = combination_items[i][0]
.

Can't get it to work, even with the default arguments, ie. "LoadCombination()"

**To Reproduce**
1. Create 1 or more LoadCases
2. Run LoadCombination(...) or LoadCombination()
3. See error

**Expected behavior**
A loadcombination with default parameters according to 
                         no: int = 1,
                   analysis_type = AnalysisType.ANALYSIS_TYPE_STATIC,
                   design_situation: int = 1,
                   name: str = '',
                   static_analysis_settings: int = 1,
                   consider_imperfection: bool = False,
                   consider_initial_state: bool = False,
                   structure_modification: bool = False,
                   to_solve: bool = True,
                   combination_items = [[1.5, 1, 0, False]],
                   comment: str = '',
                   params: dict = None,
                   model = Model):

Seems to be an issue with the combination_items argument.

**Comment by BjornSchweder** [comment]
Found a workaround, which is just adding all the loads into a single loadcase instead.

**Comment by OndraMichal** [comment]
Hi @BjornSchweder,
thank you for the reaction. I checked it via our test (.\UnitTests\test_loadCombination.py) and I don't see any issue in the latest version of RFEM. Could you provide better description? Version of the RFEM, version of the Client and even relevant part of your script.

**Comment by OndraMichal** [comment]
Hi,
I used RFEM pkg from pypi.org (1.15.0) and RFEM v6.02.0047.244 and some newer versions and no issue. Certainly with 'factor'. You can reinstall the package to make sure you haven't introduced any changes. Inadvertently using a different or tampered version of the client is a common problem.

![image](https://user-images.githubusercontent.com/37547309/225823315-21cb4edb-ffa2-4548-ac33-c4454134d82c.png)

```
# from RFEM.enums import NodalSupportType, LoadDirectionType, MemberLoadDistribution, MemberLoadDirection
from RFEM.enums import *
from RFEM.initModel import *
from RFEM.BasicObjects.material import Material
from RFEM.BasicObjects.section import Section
from RFEM.BasicObjects.node import Node
from RFEM.BasicObjects.line import Line
from RFEM.BasicObjects.member import Member
from RFEM.TypesForNodes.nodalSupport import *
from RFEM.LoadCasesAndCombinations.staticAnalysisSettings import StaticAnalysisSettings
from RFEM.LoadCasesAndCombinations.stabilityAnalysisSettings import StabilityAnalysisSettings
from RFEM.LoadCasesAndCombinations.loadCase import LoadCase
from RFEM.LoadCasesAndCombinations.loadCombination import LoadCombination
from RFEM.Loads.memberLoad import *
from RFEM.Calculate.meshSettings import GetModelInfo
from RFEM.TypesForNodes.nodalSupport import setNodalSupportConditions
from RFEM.Results.resultTables import ResultTables
from RFEM.Reports.html import *
from RFEM.Reports.printoutReport import *
from RFEM.ImportExport.exports import *
from RFEM.TypesForMembers.memberHinge import *

import numpy as np
import pandas as pd
import re

Model(new_model=True, model_name = 'Referensmodell_struktur_python')
Model.clientModel.service.begin_modification()

SetAddonStatus(Model.clientModel, AddOn.structure_stability_active)

#Geometrically Linear Static analysis
StaticAnalysisSettings.GeometricallyLinear(no=1, name = 'Fully Linear')

#Linear Buckling Modes
StabilityAnalysisSettings.EigenvalueMethod(1,'Eigenvector Linear' , 10, True, False, None, None,
StabilityAnalysisSettingsEigenvalueMethod.EIGENVALUE_METHOD_LANCZOS,
StabilityAnalysisSettingsMatrixType.MATRIX_TYPE_STANDARD)

#Create load case and combinations.
LoadCase.StaticAnalysis(no=1,
name='Lineload + Prestress',
to_solve = True,
analysis_settings_no = 1,
self_weight = [False],
params = {'calculate_critical_load': True, 'stability_analysis_settings': 1})

LoadCombination()
Model.clientModel.service.finish_modification()
```

**Comment by BjornSchweder** [comment]
Alright, I'll look into that. Thanks for the help!
