### ISSUE TITLE
BUG: ResultTables.CriticalLoadFactors()

### ISSUE THREAD

**Issue by BjornSchweder** [Dlubal-Software/RFEM_Python_Client#229]
**Describe the bug**
**ResultTables.CriticalLoadFactors()** returns ' ' , even with a loadcase defined with the 'calculate critical load' parameter enabled.
Similar commands in the ResultTables module seem to work as expected, example **ResultTables.MembersInternalForces()**

**Expected behavior**
A list of critical load factors for the calculation conducted. The lists produced by ResultTables are usually hard to discern but valuable data can be extracted. 

Similar results are found when trying a surface exclusive commands (for example **ResultTables.SurfacesEquivalentStressesMises()**) on a model using strictly members. 

`
from RFEM.enums import *
from RFEM.initModel import *
from RFEM.BasicObjects.material import Material
from RFEM.BasicObjects.section import Section
from RFEM.BasicObjects.node import Node
from RFEM.BasicObjects.line import Line
from RFEM.BasicObjects.member import Member
from RFEM.TypesForNodes.nodalSupport import *
from RFEM.LoadCasesAndCombinations.staticAnalysisSettings import StaticAnalysisSettings
from RFEM.LoadCasesAndCombinations.stabilityAnalysisSettings import StabilityAnalysisSettings
from RFEM.LoadCasesAndCombinations.loadCase import LoadCase
from RFEM.LoadCasesAndCombinations.loadCombination import LoadCombination
from RFEM.Loads.memberLoad import *
from RFEM.Calculate.meshSettings import GetModelInfo
from RFEM.TypesForNodes.nodalSupport import setNodalSupportConditions
from RFEM.Results.resultTables import ResultTables
from RFEM.Reports.html import *
from RFEM.Reports.printoutReport import * 
from RFEM.ImportExport.exports import * 
from RFEM.TypesForMembers.memberHinge import * 

import numpy as np
import pandas as pd
import re

Model(new_model=False, model_name = 'Referensmodell_struktur_python')
Model.clientModel.service.begin_modification()

#Geometrically Linear Static analysis
StaticAnalysisSettings.GeometricallyLinear(no=1,
                                           name = 'Fully Linear')

#Linear Buckling Modes
StabilityAnalysisSettings.EigenvalueMethod(1,'Eigenvector Linear' , 10, True, False, None, None, 
                                           StabilityAnalysisSettingsEigenvalueMethod.EIGENVALUE_METHOD_LANCZOS, 
                                           StabilityAnalysisSettingsMatrixType.MATRIX_TYPE_STANDARD)

#Create load case and combinations. 
LoadCase.StaticAnalysis(no=1,
                        name='Lineload + Prestress',
                        to_solve = True,
                        analysis_settings_no = 1,
                        self_weight = [False],
                        params = {'calculate_critical_load': True, 'stability_analysis_settings': 1})

MemberLoad.Force(no=1,
                 load_case_no=1,
                 members_no = '28,61',
                 load_distribution =  MemberLoadDistribution.LOAD_DISTRIBUTION_UNIFORM,
                 load_direction =  MemberLoadDirection.LOAD_DIRECTION_GLOBAL_Z_OR_USER_DEFINED_W_TRUE,
                 load_parameter =[36e3 + 4.8e3]) #30 kN utbredd last. 

MemberLoad.InitialPrestress(no=2,
                            load_case_no= 1,
                            members_no = '32,31,68,64,65',
                            load_direction= MemberLoadDirection.LOAD_DIRECTION_LOCAL_X,
                            magnitude = 600e3) #600 kN förspänning. 

NodalSupport(no = 6, support = NodalSupportType.FREE, 
              params = {'name': "Tryckbom_param", 'nodes': "58 59 113 114",'spring_x': 0,'spring_y': 11e6,'spring_z': 0, 'coordinate_system' : 1})

Calculate_all()
clf = ResultTables.CriticalLoadFactors()
print(clf)
`

**Comment by BjornSchweder** [comment]
Using Model.clientModel.service.export_result_tables_to_csv("path") is a decent workaround, it creates a folder with seperate csv sheets for different results, for example  'LC1_stability_analysis_critical_load_factors', then use pandas to read the worksheet. 

Would be nice to just extract the results directly without having to create and read files, especially for parametric study purposes.

**Comment by OndraMichal** [comment]
Hi @BjornSchweder,
CriticalLoadFactors table seems to be really empty. But I can't tell if it should be empty or not. For this, I need your sample code to be complete so I can run it and compare results in RFEM to exported table.

**Comment by BjornSchweder** [comment]
Thank you for helping, and sorry for the delayed response!

The code I'm using is for editing an already existing client model, the RFEM-model is attached below:

-------
from RFEM.enums import *
from RFEM.initModel import *
from RFEM.BasicObjects.material import Material
from RFEM.BasicObjects.section import Section
from RFEM.BasicObjects.node import Node
from RFEM.BasicObjects.line import Line
from RFEM.BasicObjects.member import Member
from RFEM.TypesForNodes.nodalSupport import *
from RFEM.LoadCasesAndCombinations.staticAnalysisSettings import *
from RFEM.LoadCasesAndCombinations.stabilityAnalysisSettings import *
from RFEM.LoadCasesAndCombinations.loadCase import LoadCase
from RFEM.LoadCasesAndCombinations.loadCombination import LoadCombination
from RFEM.Loads.memberLoad import *
from RFEM.Imperfections.imperfectionCase import *
from RFEM.Calculate.meshSettings import GetModelInfo
from RFEM.TypesForNodes.nodalSupport import setNodalSupportConditions
from RFEM.Results.resultTables import ResultTables
from RFEM.Reports.html import *
from RFEM.Reports.printoutReport import * 
from RFEM.ImportExport.exports import * 
from RFEM.TypesForMembers.memberHinge import * 

import numpy as np
import pandas as pd
import re

Model(new_model=False, model_name = 'Referensmodell_struktur_python')
Model.clientModel.service.begin_modification()
Model.clientModel.service.delete_all_results()

#What load cases are to be calculated
lin = Model.clientModel.service.get_load_case(1)
lin.to_solve = True
Model.clientModel.service.set_load_case(lin)


deltaP = Model.clientModel.service.get_load_case(3)
deltaP.to_solve = False
Model.clientModel.service.set_load_case(deltaP)


nonlin = Model.clientModel.service.get_load_case(4)
nonlin.to_solve = False
Model.clientModel.service.set_load_case(nonlin)


Calculate_all()
test = ResultTables.CriticalLoadFactors()
print(test)
-------
[Referensmodell_struktur_python.zip](https://github.com/Dlubal-Software/RFEM_Python_Client/files/11030111/Referensmodell_struktur_python.zip)

**Comment by OndraMichal** [comment]
Hi @BjornSchweder,
this is seems to be a bug. Thank you for reporting.

**Comment by OndraMichal** [comment]
Fixed
![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/37547309/20f3d0f3-d888-4d39-85cd-10bad91cc148)
