### ISSUE TITLE
BUG/REQUEST: 

### ISSUE THREAD

**Issue by Dervis-vL** [Dlubal-Software/RFEM_Python_Client#242]
**Describe the bug**
Hi,

I am trying to create result combinations with the RFEM 6 API through Python. I cannot specify which load cases, factors and operators to take into account when creating a result combination through the API. Looking at the documentation available, it seems that this class is incomplete and needs to be developed. 
Is there any way through Python to specify result combinations including load cases, factors and operators? If not, when can I expect the ResultCombination class to be updated?

**Expected behavior**
Expect to be able to have the features to define a ResultCombination as in th GUI:
- Specify which load case to include
- Specify which related factors to include
- Specify which operator to include

**Screenshots**
![image](https://user-images.githubusercontent.com/65704977/231190260-3e7e83fc-e7d7-46ea-b3dc-ef749869d5b0.png)

**Desktop (please complete the following information):**
 - Version of WIN10 OS: [WIN 10 20H2]
 - Version of RFEM6 [6.02.0056]
 - Version of tool [1.15.0]

**Comment by OndraMichal** [comment]
Hi @Dervis-vL,
thank you for the request. The Result Combination class should be updated for sure. But you can use it even in its current state. Envoking `print(model1.factory.create('ns0:result_combination'))` will give you an idea about structure of the result_combination object. If there is every parameter needed than create such parameter via `model1.factory.create('ns0:result_combination')`. Set parameters by `set_result_combination`, or add all parameters via `params` attribute as dictionary:
`ResultCombination(params={'name': ..., 'srss_combination': ..., 'srss_extreme_value_sign': ..., 'srss_use_equivalent_linear_combination': ...})`.

**Comment by OndraMichal** [comment]
Hi @Dervis-vL,
for that the easiest way is to create such object in RFEM and use WS to print it out via `print(Model.clientModel.service.get_result_combination(1))`. it will give you something like the following giving you idea about values and types of the parameters.
```
(result_combination){
   no = 1
   design_situation = 1
   user_defined_name_enabled = True
   name = "Result combination 1"
   to_solve = True
   comment = None
   combination_type = "COMBINATION_TYPE_GENERAL"
   srss_combination = False
   items =
      (array_of_result_combination_items){
         result_combination_items[] =
            (result_combination_items_row){
               no = 1
               description = None
               row =
                  (result_combination_items){
                     case_object_item = 1
                     operator_type = "OPERATOR_AND"
                     left_parenthesis = False
                     right_parenthesis = False
                     case_object_factor = 1.0
                     case_object_load_type = "LOAD_TYPE_PERMANENT"
                  }
            },
            (result_combination_items_row){
               no = 2
               description = None
               row =
                  (result_combination_items){
                     case_object_item = 2
                     operator_type = "OPERATOR_AND"
                     left_parenthesis = False
                     right_parenthesis = False
                     case_object_factor = 1.0
                     case_object_load_type = "LOAD_TYPE_PERMANENT"
                  }
            },
            (result_combination_items_row){
               no = 3
               description = None
               row =
                  (result_combination_items){
                     case_object_item = 3
                     operator_type = "OPERATOR_OR"
                     left_parenthesis = False
                     right_parenthesis = False
                     case_object_factor = 1.0
                     case_object_load_type = "LOAD_TYPE_PERMANENT"
                  }
            },
            (result_combination_items_row){
               no = 4
               description = None
               row =
                  (result_combination_items){
                     case_object_item = 2
                     operator_type = "OPERATOR_OR"
                     left_parenthesis = False
                     right_parenthesis = False
                     case_object_factor = 1.0
                     case_object_load_type = "LOAD_TYPE_PERMANENT"
                  }
            },
            (result_combination_items_row){
               no = 5
               description = None
               row =
                  (result_combination_items){
                     case_object_item = 3
                     operator_type = "OPERATOR_AND"
                     left_parenthesis = False
                     right_parenthesis = False
                     case_object_factor = 1.0
                     case_object_load_type = "LOAD_TYPE_PERMANENT"
                  }
            },
            (result_combination_items_row){
               no = 6
               description = None
               row =
                  (result_combination_items){
                     case_object_item = 4
                     operator_type = "OPERATOR_NONE"
                     left_parenthesis = False
                     right_parenthesis = False
                     case_object_factor = 1.0
                     case_object_load_type = "LOAD_TYPE_TRANSIENT"
                  }
            },
      }
   ...
 }
```

**Comment by OndraMichal** [comment]
Update of Result Combination is in progress. I'm pushing it as far as I can.

**Comment by OndraMichal** [comment]
Result Combination class is prepared for PR. See branch [dogukaratas-resultCombinationUpdate](https://github.com/Dlubal-Software/RFEM_Python_Client/tree/dogukaratas-resultCombinationUpdate).

**Comment by dogukankaratas** [comment]
Hi @Dervis-vL,
PR [254](https://github.com/Dlubal-Software/RFEM_Python_Client/pull/254) has created acc. to your comments.
