### ISSUE TITLE
BUG: Method not found: 'RfemModel.RfemModelPort.get_all_object_numbers_by_type'

### ISSUE THREAD

**Issue by kozaq9** [Dlubal-Software/RFEM_Python_Client#247]
**Describe the bug**
Method not found: 'RfemModel.RfemModelPort.get_all_object_numbers_by_type'

**To Reproduce**
1. Run every code (lets say from examples)
2. The problem occurs in the line with the loadcase
3. The exact location of the problem: RFEM\Tools\GetObjectNumbersByType.py", line 21, in __new__ObjectNumber = Model.clientModel.service.get_all_object_numbers_by_type(ObjectType.name)
4. Finally, following information: Method not found: 'RfemModel.RfemModelPort.get_all_object_numbers_by_type'

**Expected behavior**
Code should start the calculations in RFEM

**Screenshots**
![image](https://user-images.githubusercontent.com/131395362/233448946-ea74f35d-ef5e-4b4f-a137-5355b980eb52.png)

**Desktop:**
 - Version of WIN10 OS: [WIN 11 22H2]
 - Version of RFEM6 6.02.0014
 - Version of tool (?)

**Comment by MFE-VIRO** [comment]
I have exactly the same problem on my desktop workstation but I have RFEM6 version 6.02.0059. On my laptop however this problem does not occur. I don't know what's the difference between the two systems.

**Comment by OndraMichal** [comment]
Hi @MFE-VIRO, @kozaq9,
be sure to use latest Python Client with appropriate version of RFEM. We always validate the Client this way. We do our best to have source code in the shape meaning all unit tests and examples running except for functionality that is not yet released in RFEM. RFEM 1.16.00 from pypi.org was released April 13, 2023 so compatible version of RFEM is 6.02.0060. Even the following version (6.02.0061) works without problems. We don't release very often but source code here in Github should always be up to date.

**Comment by MFE-VIRO** [comment]
The problem doesn't occur anymore on my desktop workstation. I don't exactly know why. Yesterday I updated Python to 3.11.3 but that didn't solve the problem. The only thing I did next was unpacking the RFEM_Python_Client-main.zip to my working directory and run some of the files and now, all of a sudden, it works. As I have to wait on my IT department for installing RFEM 6.02.0060, I'm still using 6.02.0059. So that wasn't causing the problem.

**Comment by kozaq9** [comment]
Hi,
I have the same problem as @MFE-VIRO. I updated both RFEM and Python (RFEM 6.02.0061 and Python 3.11.3) and I have exactly the same issue as earlier. @OndraMichal, do you have any other ideas?
I tried to run my own code, as well as Demo1. The results are unfortuantely the same - it is not working - the problem is with the function called "LoadCase". I tried to run my own code and Demo1 without this function and earlier steps work perfectly fine (creating nodes, lines, surfaces, materials, thicknesses etc.).

**Comment by MFE-VIRO** [comment]
First of all: I don't consider myself as a programmer. But with my very limited knowledge of programming I tried to collect some additional information about this bug. As said before the problem only occurs on my desktop workstation and not on my laptop. So I wanted to compare the way both systems step through the code of Demo1.py (Cantilever) by debugging it in VS code. In launch.json I added the configuration "justMyCode": false. I created a breakpoint at line 47 of Demo1.py. After starting debugging using F5 in Demo1.py I stepped through the code using F11 (step into) (after it had reached line 47 in Demo1.py) except for lines 141 to 153 in LoadCase.py where I used F10 (step over). As I'm not so skilled in debugging I typed the lines I was stepping through manually in an Excel worksheet. First I did this for the desktop workstation until the line where it aborted (line 198 in runpy.py). This was quite time consuming. Then I debugged the same file (Demo1.py) on my laptop and compared the lines it was stepping through with the Excel worksheet. I found out that after line 522 in client.py (in the class MethodSelector) the laptop stepped to line 525 and the desktop workstation stepped to line 523. Using watches while pausing on line 522 I found out that at line 522 the variable m was None only on my desktop workstation. On my laptop m.name was 'get_all_object_numbers_by_type'. Unlike on my laptop, on my desktop workstation I could not find the method 'get_all_object_numbers_by_type' under _MethodSelector__methods. 

I hope this information is helpful in any way.

**Comment by OndraMichal** [comment]
Hi,
I think I runned into comparable issues lately. This seems to be issue with SUDS cache. To speedup the slow process of using web services we added caching (initModel.py, lines 40, 41). But SUDS can't differ between versions of WSDL is is caching hence there are old versions of WSDL which doesn't get updated with newer version of RFEM. This has been updated in branch [dogukaratas-resultCombinationUpdate](https://github.com/Dlubal-Software/RFEM_Python_Client/tree/dogukaratas-resultCombinationUpdate) which should be merged soon. Preferably today. 

A routine was added to delete any cached WSDL files older than 24h (initModel.py, lines 39-46).
```
# Delete cached WSDL older than 1 day to reflect newer version of RFEM
cacheLoc = os.path.join(gettempdir(), 'WSDL')
currentTime = time.time()
for file in os.listdir(cacheLoc):
    filePath = os.path.join(cacheLoc, file)
    if (currentTime - os.path.getmtime(filePath)) > 86400:
        os.remove(filePath)
```

**Comment by MFE-VIRO** [comment]
With the adjusted initModel.py this error doesn't seem to occur anymore on my desktop workstation, but on both my computers LoadCombination issue #249 is not solved.

**Comment by OndraMichal** [comment]
Is this issue still active in your versions? May I close it?

**Comment by OndraMichal** [comment]
No reaction, so I'm closing the issue.
