### ISSUE TITLE
LoadCombination issue

### ISSUE THREAD

**Issue by noahdisseldorp** [Dlubal-Software/RFEM_Python_Client#249]
I'm not much of a coder, my apologies if I am simply making a mistake, however, it seems as though the LoadCombination function isn't functioning properly. I've run the test_loadCombination function as well as the loadcombination function in my own project, in both instances have I received  the same error message: "Server raised fault: 'value: items: row: amplitude_function_type: Enumeration item '' not found. ' "
The amplitude_function_type is something that doesn't show up in the definition of the function. I've tried to solve this by addig it as a parameter without success.

Of course there still exists the possibility that I've missed something. Nevertheless I suspect this is an issue which isn't caused by my own coding inadequacies. Below I pasted a screen shot of the error which arised after running the test_loadingCombination() function.

My apologies if I'm not going through the proper channels, as you might have gathered I'm rather new to this.

![Load_combination_RFEM_python_issue](https://user-images.githubusercontent.com/131344572/234238362-6b13cfb4-6d68-4bf6-bab8-e0a7c1bc6d2b.png)

**Comment by OndraMichal** [comment]
Hi @noahdisseldorp,
thank you for the question. I executed this test with latest Python Client (main branch) and latest RFEM release and I have to say I don't see any issues. My only advice is to update both to the latest version and try it again.

**Comment by OndraMichal** [comment]
Hi @noahdisseldorp,
looking at issue #247 this could have similar cause. See https://github.com/Dlubal-Software/RFEM_Python_Client/issues/247#issuecomment-1532477864

**Comment by MFE-VIRO** [comment]
I'm getting the same error on both of my workstations, even after adjusting initModel.py as stated by @OndraMichal in issue #247.

**Comment by noahdisseldorp** [comment]
Hi @OndraMichal, 
It's been a month, I had stopped using the LoadCombination function altogether seeing as the now newly implemented ResultCombination did what I required. However, out of simple curiosity, I decided to give the LoadCombination function another try. Weirdly enough it now works without applying any changes. I'll close the issue with this comment.

I don't know if this is the right place to mention it. But I encountered a typo in the SurfaceResultAdjustment function.
Specifically in the following line: 
- clientObject.angular_rotaSurfaceResultsAdjustmentShapetion = dimensions[1]

I adjusted **angular_rotaSurfaceResultsAdjustmentShapetion** to **angular_rotation** after which the function worked fine.

        # Surface Result Adjustment Dimensions
        if shape == SurfaceResultsAdjustmentShape.SHAPE_RECTANGLE:
            clientObject.dimension_1 = dimensions[0]
            clientObject.dimension_2 = dimensions[1]
            clientObject.angular_rotation = dimensions[2]
        elif shape == SurfaceResultsAdjustmentShape.SHAPE_CIRCLE:
            clientObject.dimension_1 = dimensions[0]
            clientObject.angular_rotaSurfaceResultsAdjustmentShapetion = dimensions[1]
        elif shape == SurfaceResultsAdjustmentShape.SHAPE_ELLIPSE:
            clientObject.dimension_1 = dimensions[0]
            clientObject.dimension_2 = dimensions[1]
            clientObject.angular_rotation = dimensions[2]
