### ISSUE TITLE
REQUEST: ResultTables with Member/Object numbers and default object_no = 0

### ISSUE THREAD

**Issue by gvandewiel86** [Dlubal-Software/RFEM_Python_Client#250]
**Is your feature request related to a problem? Please describe.**
When retrieving a ```ResultTables``` (in my case ```MemberInternalForces```) with the ```object_no =0``` (as discussed during the course in NL last week) the member numbers are stripped from the output. Which makes if difficult to work with the provided output.
It seems this is due to a (uncontrollable) setting in the ```ResultTables``` class methods which all return ```ConvertResultsToListOfDct``` with the ```includeBase``` variable set to False, which in turn strips the ```no``` of from the output.

**Describe the solution you'd like**
- Change to default ```object_no``` value to ```0``` to output all objects by default.
- Provide extra optional parameter in the function call to control the ```includeBase``` parameter in the ```ConvertResultsToListOfDct``` function
  - Or even better (```if object_no == 0 and includeBase=False: includeBase = True```)

**Describe alternatives you've considered**
Don't use the support functions and make the SOAP calls and ```ConvertResultsToListOfDct``` call directly from application code:
```python
_InnerForces = Model.clientModel.service.get_results_for_members_internal_forces(
     CaseObjectType.E_OBJECT_TYPE_LOAD_CASE.name, 2, 0)

InnerForces = ConvertResultsToListOfDct(_InnerForces, True)
```
**Additional context**

**Comment by OndraMichal** [comment]
@gvandewiel86 please review changes in **PR#253** and check if this solution corresponds to your suggestion. You can add your comments here.

**Comment by gvandewiel86** [comment]
Hi Ondřej and Dogukan,

i did a quick check on the output of internal member forces and it worked quite well.
Personally i would change the default value of `include_base` to True as working with the output tables without any reference to beams no seems a bit cumbersome but given the backwards compatible behavior i understand that it is disabled by default.

Thanks for the quick solution and keep up the good work.
