### ISSUE TITLE
BUG: `Model.clientModel.service.finish_modification()` causes error since version "1.18.0"

### ISSUE THREAD

**Issue by Dervis-vL** [Dlubal-Software/RFEM_Python_Client#296]
**Describe the bug**
`Model.clientModel.service.finish_modification()` causes an error since version "1.18.0" of the rfem package.

**To Reproduce**
Create a structure with loads and combinations and result combinations. 
call `Model.clientModel.service.finish_modification()` to finish modification and run calculation. 

**Expected behavior**
I expect, as what happened in version "1.17.0" the calculation to run, not give an error.

**Desktop (please complete the following information):**
 - Version of WIN10 OS: [WIN 10 20H2]
 - Version of RFEM6 
 - Version of tool 1.18.0

**Comment by OndraMichal** [comment]
Hi @Dervis-vL,
this is usually sign of problem inside the routine, not with finish_modification function itself. If you can share the script here or send it to ondrej.michal@dlubal.cz, I can investigate further.

**Comment by OndraMichal** [comment]
Should be resolved. No script was sent and nobody else reported this issue.
