### ISSUE TITLE
BUG: I can not use Model Check functions

### ISSUE THREAD

**Issue by IcareIbnFirnas** [Dlubal-Software/RFEM_Python_Client#298]
Description of the bug :
I can not use Model Check functions like GetNotConnectedMembers or GetIdenticalNodes. Maybe I use them badly because I have an issue on Python when I use it (see the atteched screenshots).

Please free to contact me if you have any solution or a beggining of a solution or to know more about the problem.
Have a nice day,
![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/148334709/f590c649-769c-48f1-8f6a-ffab4276a3bd)
![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/148334709/d1406caa-9100-4b4d-83e3-8ee0f4c979db)

**Comment by OndraMichal** [comment]
Hi @IcareIbnFirnas,
sadly functions from ModelCheck.py are not released in RFEM, yet.

**Comment by IcareIbnFirnas** [comment]
Hello thansk for the answer,
When do you think it will be available in RFEM6 ?
Kind regards,
