### ISSUE TITLE
BUG: How can I assign "Permanent and transcient" ULS in an accidental case

### ISSUE THREAD

**Issue by IcareIbnFirnas** [Dlubal-Software/RFEM_Python_Client#299]
Good morning,
I try to automatize my computations with Python but I can't assign "Permanent and transcient" ULS in an accidental case. By default it's on "Fire verification" but I want to switch it automatically in "Permanent and transcient". If you have information about that, I would be grateful to know how to fix that !
I joined a screenshot of the problem.

![Capture](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/148334709/582f3194-7494-40e4-82b3-e10026ec2578)

**Comment by OndraMichal** [comment]
Hi @IcareIbnFirnas,
thank you for the post. In order to come up with a solution, it's best to provide part or all of the script (to provide context) so we can test if you make a mistake somewhere or there is mistake in our implementation.

**Comment by IcareIbnFirnas** [comment]
Hello, thank you for your answer, where can I send you the script ?

**Comment by Sacek073** [comment]
Hello @IcareIbnFirnas please upload your script as a comment here. Thank you very much.

**Comment by OndraMichal** [comment]
Hi @IcareIbnFirnas,
thank you for the script. I tried to imitate your issue but I'm not sure if I'm doing the same thing as you do. In your code, I can't find the part where it should switch to Permanent and transcient. More over I have to clip out the part you are talking about because I'm missing defined pathway (Z:/9. Direction Technique/...) at minimum. Could you provide step by step instruction?

**Comment by dogukankaratas** [comment]
Hi @IcareIbnFirnas,

We navigated thorugh our Core API regarding to your question but this feature is not possible yet. We started to work on it and let you know when its done.

**Comment by IcareIbnFirnas** [comment]
Hello @dogukankaratas  thank you for your answer. When do you think it will be available ?
Kind regards,

**Comment by IcareIbnFirnas** [comment]
Hello, I can not send you an email because Dlubal.local rejected my message 
![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/148334709/6bf929b1-6613-4d89-98ce-1235e28a035c)

**Comment by heetrojivadiya** [comment]
Hello @IcareIbnFirnas, 

Unfortunately, there is no direct connection for the addon design situation type with the Webservice. However, you can still access it via JavaScript and call that .js file using the `run_script()` method in the Webservice. I have attached a small demo example with the require function to edit the addon design situation type. You can paste that function into your code and then call it with the number for which addon design situation type you want to change.

```py
import os
baseName = os.path.basename(__file__)
dirName = os.path.dirname(__file__)
print('basename:    ', baseName)
print('dirname:     ', dirName)

from RFEM.enums import *
from RFEM.initModel import Model, SetAddonStatus
from RFEM.LoadCasesAndCombinations.designSituation import DesignSituation

def AddOnDesignSituationType(no: int = 1, situation_type = 6195):

    '''
    6145	ULS (STR/GEO) - Accidental
    6155	ULS (STR/GEO) - Accidental - Fire
    6193	SLS - Characteristic
    6194	SLS - Frequent
    6195	SLS - Quasi-permanent
    7220    SLS - Vibration
    6326	ULS (STR/GEO) - Permanent and transient
    '''

    with open(dirName+r"./design_situation.js", "w") as std:

        std.write("STEEL_DESIGN.design_situations[{}].addon_design_situation_type = {};".format(no, situation_type))

    Model.clientModel.service.run_script(dirName+r"./design_situation.js")

    os.remove(dirName+r"./design_situation.js")

Model(True, 'Steel')
SetAddonStatus(Model.clientModel, AddOn.steel_design_active)
DesignSituation(3, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_ACCIDENTAL_PSI_1_1)
AddOnDesignSituationType(3,6326)
```
![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/108512789/7a787d10-faa0-4b96-b5ef-8ed1836f955a)
