### ISSUE TITLE
BUG: How to assign the modal anaylisis with Python

### ISSUE THREAD

**Issue by IcareIbnFirnas** [Dlubal-Software/RFEM_Python_Client#300]
Good morning, 
With my code in Python, I can't put ModalAnalysisSettings as I do with StaticAnalysisSettings. 
Is there any function to do the modal analysis with Python ?
Tkank you very much for your answers !

![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/148334709/0cdc9d8b-f8a8-4cc6-af85-521ee497e7e9)
![Capture](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/148334709/f1c5845e-b052-4044-b37d-4d0391b02019)

**Comment by OndraMichal** [comment]
Hi @IcareIbnFirnas,
again the script needs to be provided to check if everything works as it should. Web Services tend to be very particular regarding types of the values.

**Comment by IcareIbnFirnas** [comment]
Hello @OndraMichal , where can I send you my script ?

**Comment by IcareIbnFirnas** [comment]
Actually, the problem is that I can define : Loadcase.StaticAnalysis but there is no key work for ModalAnalysis in the script of Loadcase present here : RFEM_Python_Client-main\RFEM\LoadCasesAndCombinations
