### ISSUE TITLE
REQUEST: Results Table Manager

### ISSUE THREAD

**Issue by gvandewiel86** [Dlubal-Software/RFEM_Python_Client#303]
**Is your feature request related to a problem? Please describe.**
When retrieving results from a model we would like to only retrieve the result in the start and end node of  a beam.
As far as i can see there is no way to alter the the format of the Results Table via the python / WS interface.
What we would like, is to achieve the following settings via python script and restore to the default settings afterwards:
![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/103375087/dad209f9-2031-4dcd-8fac-b4413c2c8ad1)

This would produce a table output like this:
![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/103375087/dcde36fd-fade-4d1d-874a-dc8873353bc7)

By default, the data served via the WS is exactly the same as show in the figure below it is "difficult" to filter the start and end node (i am not saying it is impossible however not having to filter the data via python is much faster).
![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/103375087/55dc7f52-f15c-4cec-b9c5-62b9dd68827b)

**Describe the solution you'd like**
Add the option to control the output (look and feel) of the Resutls Table per output type.

**Describe alternatives you've considered**
Manually preparing the output tables prior to running the script.

**Additional context**

**Comment by TomasPail** [comment]
As first step, we are now going respect the settings of Result Table Manager in the output of Webservice operations related to results. For now, It's not planned to provide a Webservice function to access settings of Result Table Manager because of the high complexity.

**Comment by gvandewiel86** [comment]
@TomasPail,

thanks for the update. That would be a good starting point and would be a tremendous time saver for us.

Regarding the support to access the Result Table Manager, I was under the impression that this was already supplied via WS, using `GetTableExportConfigManager` and `SetTableExportConfigManager`?

**Comment by gvandewiel86** [comment]
Pushed the wrong button during reply…
My bad…
