### ISSUE TITLE
REQUEST: Move the "connect to server" logic in a function

### ISSUE THREAD

**Issue by gvandewiel86** [Dlubal-Software/RFEM_Python_Client#304]
**Is your feature request related to a problem? Please describe.**
When using the python RFEM library with for instance xlwings the module is automatically imported when opening the excel file (behavior of xlwings). However, the end user won't always have an active model (or even RFEM) open and due to setup of the initModel.py to program throws all kinds of errors that no connection with the RFEM program is possible forcing an exit from all routines.

As we are planning to integrate the python library with excel using xlwings it would be nice to have a bit more user control over the moment a connection is made with the RFEM application (or server).

**Describe the solution you'd like**
A function to try to connect to the RFEM program with a more graceful return.
Furthermore it would be more beneficial if the use of global objects (`Model`, `client`, `ca` and `url`) is restricted and stored in a separate module as described in Python's document on [sharing global variables across modules](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules).

Perhaps I am missing some other ways / options to control the connection process to RFEM and other solutions would be highly appreciated.

**Describe alternatives you've considered**
Currently i have patched the `initModel.py` to have such a function and manually exposed the four variables for the other RFEM modules to use.

**Additional context**

**Comment by gvandewiel86** [comment]
It seems that this enhancement is not implemented in the latest releases?
If i install 1.19.0 or 1.19.1 the initModel file does not contain the `connectToServer` routine.

**Comment by Sacek073** [comment]
Hi sorry for the delayed response. Right now, this enhancement is not part of the pypi package yet. If you want to use it wight now, you can clone this repository, where it is working.

**Comment by Sacek073** [comment]
Hi @gvandewiel86 sorry for the delayed response. The new release 1.19.2 is just out, so you can use it. But in the future if you need to use some functionality, which is not yet in the current release, you can always clone the repository and use it from there.

**Comment by gvandewiel86** [comment]
Hi @Sacek073,

i am aware of the cloning option but we have multiple colleagues working with tooling which is dependable on the python library which aren't all so technical. Furthermore based on the relatively high rate of changes in both the python library and RFEM software the chance of breaking changes in either the RFEM software or python library makes me want to have a bit more control over which versions we are using together. 

But thanks anyway for the comments and advice.
