### ISSUE TITLE
BUG: Add psutil to dependencies in setup.py

### ISSUE THREAD

**Issue by MaartenBW** [Dlubal-Software/RFEM_Python_Client#305]
**Describe the bug**
In the latest version of the python client, psutil added to the dependency check in dependencies.py. But in the package dependencies in setup.py, this package is not added. So whenever the package is installed fresh using pip, psutil is not installed. So this triggers the prompt to install missing dependencies. So please add psutil also to setup.py, so it is automatically installed.

In my opinion: dependencies should not be managed with custom code like this. PyPi/Pip offers excellent dependency management, so why include this code youself? With a manual prompt?

**Comment by OndraMichal** [comment]
Hi @MaartenBW,
thank you for noticing this. It'll be corrected. Regarding PyPi dependency management. It could be good but only if we don't lose dependency check when running code directly from repo.

**Comment by Sacek073** [comment]
Hello, I believe this issue was fixed in commit https://github.com/Dlubal-Software/RFEM_Python_Client/commit/e191717df342008447541ee8cdc08f5f095bdb4e

**Comment by Sacek073** [comment]
This issue was fixed in commit https://github.com/Dlubal-Software/RFEM_Python_Client/commit/489e1420baecb680722d6f2380f7a855ddc55a1e
