### ISSUE TITLE
BUG: Can't Update Global Parameter when Results are available

### ISSUE THREAD

**Issue by gvandewiel86** [Dlubal-Software/RFEM_Python_Client#306]
**Describe the bug**
Can't Update Global Parameter when Results are available

**Expected behavior**
When updating the parameter value manually we first get prompted that all results will be deleted when changing this value.
When using the `GlobalParameter.AddParameter` function we don't get prompted (obviously) but we are also not able to forcibly update the Parameter value.

**Desktop (please complete the following information):**
 - Version of RFEM6 = 6.04.0002
 - Version of tool =  1.18.0

**Comment by Sacek073** [comment]
Hello, thank you for reaching out to us. Could you please upload your script, where this error occurs? It would help us identify the source of error. I tried to foricbly update GlobalParameter by rewriting it again with `AddParameter` when there were Results available and ended up with succesful update of parameter (see the code below). 
```python
    GlobalParameter.AddParameter(
                                 no= 1,
                                 name= 'Test_1',
                                 symbol= 'Test_1',
                                 unit_group= GlobalParameterUnitGroup.LENGTH,
                                 definition_type= GlobalParameterDefinitionType.DEFINITION_TYPE_FORMULA,
                                 definition_parameter= ['1+1'],
                                 comment= 'Comment_1')
    Model.clientModel.service.calculate_all(False)
    GlobalParameter.AddParameter(
                                 no= 1,
                                 name= 'Test_1',
                                 symbol= 'Test_1',
                                 unit_group= GlobalParameterUnitGroup.LENGTH,
                                 definition_type= GlobalParameterDefinitionType.DEFINITION_TYPE_FORMULA,
                                 definition_parameter= ['4+1'],
                                 comment= 'Comment_1')
```
Version of RFEM: 6.04.0007
Version of tool: 1.19.1

**Comment by OndraMichal** [comment]
Hi,
No more comments. Issues is closed.
