### ISSUE TITLE
BUG: ResultTables.NodesSupportForces fails in ConvertResultsToListOfDct

### ISSUE THREAD

**Issue by MaximilianFranz** [Dlubal-Software/RFEM_Python_Client#311]
**Describe the bug**
Trying to access the nodal support forces of a model using `ResultTables.NodesSupportForces` with the load-case-no and the node-no. 

```pyhton
results = ResultTables.NodesSupportForces(CaseObjectType.E_OBJECT_TYPE_LOAD_CASE.name, load_case_no, node_no, model)` 
```

In `GetResultTableParameters`it tries to access `i.row.__keylist__` but the `.row` of entry with index `01` of the results is just a `Text` type, hence it fails with an `AttributeError`. 

The index `1` refers to a row which says something like :"Min/Max Analyse mit Werten", so it's not an actual result row, but rather a row shown in the RFEM frontend to structure the result table. 

**Expected behavior**
Should properly parse the result. 
Or are we accessing the `NodalSupportForces` wrong? 

**Additional context**
Workaround is currently to directly access: 

```python
model.clientModel.service.get_results_for_nodes_support_forces
```
and then get the support_forces (just interested in the first row anyways) like this: 

```python 
                raw_results = model.clientModel.service.get_results_for_nodes_support_forces(CaseObjectType.E_OBJECT_TYPE_LOAD_CASE.name, load_case_no, node_no)
                nodal_result = {"nodal_support_force_p_z": float(raw_results.nodes_support_forces[0].row.support_force_p_z.value)}
                results_per_lc_per_node[load_case_no][node_no] = nodal_result
```

this works, but it's not great, because we have to do the parsing ourselves.

**Comment by OndraMichal** [comment]
Hi @MaximilianFranz,
I'm taking over this issue. If I understand correctly, your problem is that the GetResultTableParameters() function is parsing incorrectly? IS it tru. Is it still an issue with the latest RFEM Python Client?

**Comment by MaximilianFranz** [comment]
We're using the workaround mentioned above, I have not tried again since.

**Comment by OndraMichal** [comment]
OK. 25.8.2023 there was an update (SHA-1:199515e476b3fb0d55bfd6cc5af722dc82fa78ae) to condition 'if 'row' in i.__keylist__:' since then we didn't notice any issue.

**Comment by heetrojivadiya** [comment]
tested with RFEM version 6.06.0002 and RFEM pip version 1.19.5. 
<img width="563" alt="image" src="https://github.com/Dlubal-Software/RFEM_Python_Client/assets/108512789/a1aa4400-a268-4347-8986-27a9eca98fa7">
