### ISSUE TITLE
REQUEST: Set Standards for Addons (e.g. dynamic analysis)

### ISSUE THREAD

**Issue by Lulatsch39** [Dlubal-Software/RFEM_Python_Client#321]
Hi there,
Unfortunately, I can't find a way to set or select the standard used for the dynamic anaylsis e.g. modal or response spectrum analysis. I can get the value `poperty_addon_response_spectrum_analysis` by running `model.clientModel.service.get_model_info()` but I didn't find a way to set that value though. 

It would be great if one can pass the desired standard as a parameter when setting the addon status by `SetAddonStatus()` or implement a method like `model.clientModel.service.set_model_info()`.

I hope I didn't miss anything.
Thanks.

**Comment by OndraMichal** [comment]
Hi @Lulatsch39,
what kind of standard do you have in mind? Do you mean national annexes and standards for Load Cases And Combinations (class LoadCasesAndCombinations)?

Set_model_info doesn't make sense because it would be similar to set_results. I'm looking for 'poperty_addon_response_spectrum_analysis' but there is only 'response_spectrum_analysis' in get_model_info data.

**Comment by Lulatsch39** [comment]
Hi @OndraMichal, 
yeah similar to the standards and national annexes for load cases and combinations but only for earthquake analysis (response spectrum analysis). Please see the screenshot below showing which parameter I mean.

![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/64608893/3223840e-3bf0-4a66-a10f-5d23f63783a4)

The next question would be how to edit the parameters for a generated response spectrum after selecting the standard. This question was also asked in discussion #309 . Please see on the next screenshot which parameters I'm talking about. 

![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/64608893/9fba1169-4d5c-41aa-a8a9-2951b339ef8a)

**Comment by heetrojivadiya** [comment]
> Hi @OndraMichal, yeah similar to the standards and national annexes for load cases and combinations but only for earthquake analysis (response spectrum analysis). Please see the screenshot below showing which parameter I mean.
> 
> <img alt="" width="600" src="https://private-user-images.githubusercontent.com/64608893/290806691-3223840e-3bf0-4a66-a10f-5d23f63783a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDc1NzEsIm5iZiI6MTcxMTQ0NzI3MSwicGF0aCI6Ii82NDYwODg5My8yOTA4MDY2OTEtMzIyMzg0MGUtM2JmMC00YTY2LWExMGYtNWQyM2Y2Mzc4M2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEwMDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMjA5Yjk5MTI5MWJjYmY3MTI4MWEyZDRlN2RkYWE3NDczZGEwN2NhZDNkODZkNjU2MDVhNDA4NzcwZGQzYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RHuMxEHc2yZllQ5GAGdmnvT9BruWjtrcrFAYpdm6MxE">
> The next question would be how to edit the parameters for a generated response spectrum after selecting the standard. This question was also asked in discussion #309 . Please see on the next screenshot which parameters I'm talking about.
> 
> <img alt="" width="600" src="https://private-user-images.githubusercontent.com/64608893/290807688-9fba1169-4d5c-41aa-a8a9-2951b339ef8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDc1NzEsIm5iZiI6MTcxMTQ0NzI3MSwicGF0aCI6Ii82NDYwODg5My8yOTA4MDc2ODgtOWZiYTExNjktNGQ1Yy00MWFhLWE4YTktMjk1MWIzMzllZjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEwMDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZmE0YWM2M2M2NTRhNmE1OTI3MWMwMjBjYTZkNDVmZjQyNTcxNWJkZWQ2MTBkMTFlYTNkZDI4NTFiNWMzOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7DvgK7b4ZMKrgH62i_5qg8vfRRss1hbPghF4Ky5XbIk">

Hello @Lulatsch39, 

currently, direct access to the addOn standard is not possible with Python WS. But we can set standards for AddOn via javascript and we can run that .js file with the help of `run_script()` methods in Python WS. Below you can find the demo example for how to access the standard for AddOns, You may copy and paste that function into your script and edit for any AddOns standard. 

```py
import os
baseName = os.path.basename(__file__)
dirName = os.path.dirname(__file__)

from RFEM.enums import *
from RFEM.initModel import Model, SetAddonStatus

def DynemicAnnex(standard: str = 'EN 1998-1 | CEN | 2013-05'):

    with open(dirName+r"./standard.js", "w") as std:

        std.write("general.current_standard_for_dynamic_analysis = '{}'".format(standard))   # change attribute for another AddOn (e.g. 'current_standard_for_steel_design' for Steel Design)

    Model.clientModel.service.run_script(dirName+r"./standard.js")

    os.remove(dirName+r"./standard.js")

Model(True,'Demo')
SetAddonStatus(Model.clientModel, AddOn.spectral_active)
DynemicAnnex('EN 1998-1 | DIN | 2023-11')
```

For the second question, you may refer to the answer to discussion #309. I hope the above solution will work for you. 

Thanks and best regards,
Heet Rojivadiya

**Comment by Lulatsch39** [comment]
Alright, thanks!
