### ISSUE TITLE
REQUEST: Possibility to edit timber design fire configuration

### ISSUE THREAD

**Issue by Lulatsch39** [Dlubal-Software/RFEM_Python_Client#322]
Hi there,
I'm looking for the possiblity to create and edit a fire configuration for timber design. With using `Model.clientModel.service.set_timber_design_fr_configuration(...)` I can create a configuration. Unfortunately, I can't find a way to access the important parameters marked in the screenshot below.
I tried `Model.clientModel.service.get_timber_design_fr_configuration(...)` to get an idea of the structure of the parameters but that doesn't provide any information on the marked values either.

<img src="https://github.com/Dlubal-Software/RFEM_Python_Client/assets/64608893/0f609fd3-4e35-4347-a43f-e4a5c4644d62" width="800">

Thanks in advance.

**Comment by OndraMichal** [comment]
Hi @Lulatsch39,
thank you for notifying us. Bug #163296 was created.
