### ISSUE TITLE
BUG: Missing definition of modelLst in init.Model.py

### ISSUE THREAD

**Issue by Helodin** [Dlubal-Software/RFEM_Python_Client#323]
**Describe the bug**
When starting main.py in the Examples folder via VsCode I get an import Error for line #16
![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/36902096/fbf30222-49c9-40c0-aca9-3d8b534da478)

**To Reproduce**
1. Go to ...\RFEM_Python_Client\Examples
2. Click on main.py
3. execute it

**Expected behavior**
script stops at line 16
![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/36902096/eaea424e-44a7-4854-b93f-8cd22554f5ce)

**Desktop (please complete the following information):**
 - Version of WIN10
 - Version of RFEM6

**Additional context**
I checked the referring init.model.py and it seems that the object modelLst is missing a definition in there

**Comment by VasStach** [comment]
I recently encountered the same bug. modellst object is embedded in `connectToServer` method in initModel.py. My quick solution was to return modellst out of the method and then replace modellst with connectToServer() in the main file accordingly. I hope this helped.
