### ISSUE TITLE
BUG: Angle of Layers and Stiffness Reduction are ignored in Multilayer Thicknesses

### ISSUE THREAD

**Issue by Lulatsch39** [Dlubal-Software/RFEM_Python_Client#328]
Hi there,

when creating a Thickness of type Layers with the Multilayer Surfaces Add-On I can't define the angle of the different layers. As written in the documentation I provide a list of lists for the layers as followed: 
```
layers = [['E_THICKNESS_TYPE_DIRECTLY', 2, 0.04, 0], ['E_THICKNESS_TYPE_DIRECTLY', 3, 0.02, 90], ['E_THICKNESS_TYPE_DIRECTLY', 3, 0.02, 0], ['E_THICKNESS_TYPE_DIRECTLY', 3, 0.02, 90], ['E_THICKNESS_TYPE_DIRECTLY', 2, 0.04, 0]]
```

The materials 2 and 3 are defined with material type orthotropic:
```
Material(2, 'Stora Enso (40 mm)', params={'material_model': 'MODEL_ORTHOTROPIC_2D'})
Material(3, 'Stora Enso (20 mm)', params={'material_model': 'MODEL_ORTHOTROPIC_2D'})
```

However, the last entry of each layers list (0 or 90) is taken as a comment and not as the angle of the layer. This can be seen in RFEM in the created layers tab:

<img src="https://github.com/Dlubal-Software/RFEM_Python_Client/assets/64608893/2fbb7f35-4397-4fd8-8af9-660fa9a5a0f0" width="800">

Additionally, the provided parameters for the stiffness modification do not have any influence. The values for K33, K44, K55, K88 are ingored.
I'm using the following code to create the thickness:

```
Thickness.Layers(n, name, layers, stiffness_reduction=True, 
stiffness_modification=[[0.65, None], [1, None], [1, None], [0.7, None]],
clt_options=[[True, 100, 100], [False, 0, 0]],
params={'is_enabled_design_of_failure': True,
'plank_width_bx': 0.1,
'plank_width_by': 0.1,
'stiffness_reduction_enabled': True,
'plank_width_including_gap_enabled': False,
'K33': 0.65, 'K44': 1.0, 'K55': 1.0, 'K88': 0.7})
```

Input:
<img src="https://github.com/Dlubal-Software/RFEM_Python_Client/assets/64608893/eb5bc9fb-dcd2-4a19-8544-78510b2a97f4" width="600">

Created thickness of type layers with the stiffness reduction factors still set to 1.00 instead of 0.65 and 0.7 respectively:

<img src="https://github.com/Dlubal-Software/RFEM_Python_Client/assets/64608893/59f82687-b9d0-48dc-8af5-18d8b5a00bbd" width="600">

 - Version of WIN10 OS: [WIN 10 21H1]
 - Version of RFEM6.05.0001
 - Version of tool Release v1.19.2

**Comment by OndraMichal** [comment]
Hi @Lulatsch39,
thank you for posting this issue. I checked and the parameters you are pointing out are completely missing in the Thickness object. Reported bug 163328.

**Comment by OndraMichal** [comment]
Hi @Lulatsch39,
thank you for reporting the issue. I think it due tu missing parameter user_defined_stiffness which would unlock the feature for editing. Rreported bug 143795.
![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/37547309/9d506c26-b869-46cd-9c72-722fc0ab2f49)
