### ISSUE TITLE
BUG: Function CentreOfGravity

### ISSUE THREAD

**Issue by jlemeriel** [Dlubal-Software/RFEM_Python_Client#373]
I would like to retrieve the coordinates of the center of gravity of certain elements, selected or not in RFEM.
My code is 

from RFEM.Tools.centreOfGravityAndObjectInfo import ObjectInformation

Model(False,"Bloc 6 RFEM6.rf6") 

p=ObjectInformation.CentreOfGravity(
                    ObjectTypes.E_OBJECT_TYPE_MEMBER,
                    0,
                    1,
                    'X')
The bug is : 
File ~\.spyder-py3\RFEM\Tools\centreOfGravityAndObjectInfo.py:24 in CentreOfGravity
    result = ObjectInformation.__BuildResultsArray(object_type, no, parent_no)

  File ~\.spyder-py3\RFEM\Tools\centreOfGravityAndObjectInfo.py:84 in __BuildResultsArray
    elements = model.clientModel.factory.create('ns0:array_of_get_center_of_gravity_and_objects_info_elements_type')

  File ~\AppData\Roaming\Python\Python311\site-packages\suds\client.py:254 in create
    raise TypeNotFound(name)

TypeNotFound: Type not found: 'ns0:array_of_get_center_of_gravity_and_objects_info_elements_type'

 - Version of Python 3.11 
 - Version of RFEM6.06.0007

**Comment by heetrojivadiya** [comment]
Hello @jlemeriel ,

Thank you for reporting the bug. I have created PR #383 to fix this bug. After successful merging of it, this bug should be fixed. If you still face the issue then feel free to contact us.
