### ISSUE TITLE
BUG: Excessive Node results

### ISSUE THREAD

**Issue by cslotboom** [dlubal-software/RFEM_Python_Client#392]
**Describe the bug**
Results for node supports from seem to kick out duplicates. 
In the code below I request data from one load combo (combo 9), and would expect to receive one results, instead multiple.

**To Reproduce**
Run the code below on a model.

```Python
Model(False, "test.rf6")
Model.clientModel.service.begin_modification("new")

nodes = GetObjectNumbersByType(ObjectTypes.E_OBJECT_TYPE_NODE, Model)

output = []
for node in nodes:
    output.append(ResultTables.NodesSupportForces(CaseObjectType.E_OBJECT_TYPE_LOAD_COMBINATION, 9, int(node)))
    
Model.clientModel.service.finish_modification()
Model.clientModel.service.close_connection()
```

**Screenshots**
![image](https://github.com/user-attachments/assets/e708ecff-b388-4f4e-9c1d-677f0a7de56d)

![image](https://github.com/user-attachments/assets/863178c2-5b43-4171-92a4-d1bf99c926c7)

**Desktop (please complete the following information):**
 - Version of WIN10 OS: 10.0.19044
 - Version of RFEM 6.06.0010
 - Api version 1.20.1

**Additional context**

**Comment by heetrojivadiya** [comment]
Hello @cslotboom,

Thank you for reaching to us. I have tested your issue. You are trying to get results one by one node. The result Table method give complete table as shown in RFEM. For example, if you assign node 1 to fetching the result table, it will provide a complete table like the picture below. 

<img width="634" alt="image" src="https://github.com/user-attachments/assets/8231e68e-cebf-4631-a44b-5726e2b8fdf3">

So, for the first row you can append table row with 0 index like `ResultTables.NodesSupportForces(CaseObjectType.E_OBJECT_TYPE_LOAD_COMBINATION, 9, 1)[0]`

So, the corrected code for your request is as below:

```py
from RFEM.Tools.GetObjectNumbersByType import GetObjectNumbersByType
from RFEM.Results.resultTables import ResultTables
from RFEM.enums import *

Model(False, 'test')

Model.clientModel.service.begin_modification("new")

nodes = GetObjectNumbersByType(ObjectTypes.E_OBJECT_TYPE_NODE, Model)

output = []
for node in [1]:
    result = ResultTables.NodesSupportForces(CaseObjectType.E_OBJECT_TYPE_LOAD_COMBINATION, 1, int(node))
    if len(result) != 0:
        output.append(result[0])

Model.clientModel.service.finish_modification()
Model.clientModel.service.close_connection()

for item in output:
    print(item)
```

Let us know if you still face any issue.
