### ISSUE TITLE
REQUEST: Results taking example

### ISSUE THREAD

**Issue by paireks** [Dlubal-Software/RFEM_Python_Client#78]
Hello,

it will be really helpful to have an example of taking results for mesh points / raster points using Python for specific load combinations.

Main question would be if new API provides faster method (in terms of computational time) to get these results, because for some reason taking results for already calculated model via RFEM 5 API can take few hours, which makes hard to use it via API and via Grasshopper.

Best regards ;)

**Comment by dogukankaratas** [comment]
Hi @paireks,

Thank you for the feedback. We are still working on exporting results from specified points. As soon as these functions are ready, we will create some examples for them.

After that, you can tell us your opinion about computational time :)

**Comment by Ra-Na** [comment]
I am missing such an interface as well. Did you advance? If not, is it possible to do this with JS?

**Comment by OndraMichal** [comment]
Hi,
we are advancing. Right now, corrections need to be made to the result tables exported from Web Services. Should be available soon (09/2022).

**Comment by OndraMichal** [comment]
Please see [Release v1.11.0.](https://github.com/Dlubal-Software/RFEM_Python_Client/releases/tag/R-v1.11.0)
This issue will be canceled.
