### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by CANCEL-FEM** [Dlubal-Software/RFEM_Python_Client#84]
The initiModel code has been modified recently.
With the previous commands the model can be initialized as follows (example): 
Model(True, "SEM") 
Model.clientModel.service.begin_modification("new")
But now I get AttributeError: Text object has no attribute name 
so my question is how to initialize the model?

**Comment by dogukankaratas** [comment]
Hi @CANCEL-FEM,

Thanks for the feedback. Bug fixed.
