### ISSUE TITLE
REQUEST:

### ISSUE THREAD

**Issue by CANCEL-FEM** [Dlubal-Software/RFEM_Python_Client#86]
I have several questions regarding using RFEM_Python package
First question is how to define a non-linear hinge, where the non-linearity is a diagram? 
The second one is how to define a non-linear support, where the non-linearity is friction PZ?
The third one is: Is there any function to set axial offset from adjoining member? 
The last one is what function can be used to generate load combinations?

**Comment by dogukankaratas** [comment]
Hi,
Our implementation plan can be tracked under GitHub Projects :)

**Comment by SigWil** [comment]
Hello,
I am very interested in the python interface, but for our use it is necessary to define non-linear hinges per diagram for nodes like it was asked in this post. 
So far I have not seen that it is implemented yet. Am I right?
Maybe you could explain for me what do you mean with the implementation plan. I have not found it and is there something said about this non-linear hinges?
Thanks in advance
