### ISSUE TITLE
REQUEST: Manipulation of Elements and Nodal Points (mesh only)

### ISSUE THREAD

**Issue by ricardolopezgr** [Dlubal-Software/RFEM_Python_Client#95]
Hello,

It would be really helpful to manipulate element and nodal points, specially when it comes to shell elements.

For instance, with this feature I could code things like:

1. Impose nodal displacements over the boundary nodes, thus being able to submodel from one model to another with higher detail.
2. Extract specific properties/results from nodes/elements

This feature looks promising anyway 👍, although I miss a bit of documentation! Keep up with the good work!

**Comment by OndraMichal** [comment]
Hi [ricardolopezgr](https://github.com/ricardolopezgr),
we appreciate your comments. We start from the bottom up. It will definitely take some time to get it in the shape we like. Manipulations will definitely be added in the future. But right now, we need to focus on the basics, such as results. Documentation is also in the process (see .\docs\ folder) 😉

**Comment by ricardolopezgr** [comment]
> Hi [ricardolopezgr](https://github.com/ricardolopezgr), we appreciate your comments. We start from the bottom up. It will definitely take some time to get it in the shape we like. Manipulations will definitely be added in the future. But right now, we need to focus on the basics, such as results. Documentation is also in the process (see .\docs\ folder) 😉

Nice @OndraMichal , looking fwd to exploring the features more in depth!
